<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { adminApi, type AdminAudit } from '@/l12/platform'
import PagedCollection from './PagedCollection.vue'
const audits = ref<AdminAudit[]>([]); const category = ref(''); const outcome = ref(''); const actorId = ref(''); const commandId = ref(''); const correlationId = ref(''); const loading = ref(false); const notice = ref('')
async function load() { loading.value = true; try { audits.value = await adminApi.audit({ category: category.value, outcome: outcome.value, actorId: actorId.value, commandId: commandId.value, correlationId: correlationId.value }) } catch (cause) { notice.value = cause instanceof Error ? cause.message : '审计记录读取失败' } finally { loading.value = false } }
onMounted(load)
</script>
<template>
  <section class="audit-page panel"><header><div><h2>管理与安全审计</h2><p>按操作者、命令和关联编号追溯管理动作。</p></div><div class="filters"><select v-model="category"><option value="">全部类型</option><option value="account">账号权限</option><option value="session">会话安全</option><option value="security">安全</option><option value="command">命令</option><option value="content">内容</option><option value="effect">卡效</option><option value="release">发布</option></select><select v-model="outcome"><option value="">全部结果</option><option value="succeeded">成功</option><option value="executed">已执行</option><option value="failed">失败</option><option value="denied">拒绝</option></select><input v-model="actorId" placeholder="操作者 ID"><input v-model="commandId" placeholder="命令 ID"><input v-model="correlationId" placeholder="关联 ID"><button :disabled="loading" @click="load">查询</button></div></header><p v-if="notice" class="notice">{{ notice }}</p><PagedCollection :items="audits" v-slot="{ items }"><article v-for="audit in items" :key="audit.id"><span>{{ new Date(audit.createdAt).toLocaleString() }}<small>{{ audit.actorName }}</small></span><b>{{ audit.category }} · {{ audit.action }}<small>{{ audit.outcome || 'success' }}</small></b><code>{{ audit.target }}</code><span>{{ audit.fromValue || '无' }} → {{ audit.toValue || '无' }}<small v-if="audit.comment">{{ audit.comment }}</small><code v-if="audit.correlationId">关联：{{ audit.correlationId }}</code></span></article></PagedCollection><p v-if="!audits.length && !loading">暂无管理操作记录。</p></section>
</template>
<style scoped>
.panel{padding:18px;border:1px solid #35424a;background:#0e161d}.panel>header{display:flex;align-items:flex-start;justify-content:space-between;gap:14px}.panel h2{margin:0 0 6px}.panel p,.panel small{color:#89979d}.filters{display:grid;grid-template-columns:repeat(3,minmax(120px,1fr));gap:7px}.filters button,.filters input,.filters select{box-sizing:border-box;min-height:38px;padding:7px 9px;border:1px solid #4b5961;background:#080e13;color:#fff}.panel article{display:grid;grid-template-columns:minmax(150px,.7fr) minmax(140px,.8fr) minmax(120px,.7fr) minmax(220px,1.4fr);gap:12px;padding:12px 0;border-top:1px solid #303c43}.panel article>span,.panel article>b{display:grid;gap:4px;min-width:0}.panel code{overflow-wrap:anywhere}.notice{padding:10px;border-left:3px solid #d1b25c;background:#241c0a;color:#edd584!important}
@media(max-width:950px){.panel>header{flex-direction:column}.filters{width:100%}}@media(max-width:700px){.filters{grid-template-columns:1fr}.panel article{grid-template-columns:1fr}}
</style>
