<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { adminApi, type AdminCommand } from '@/l12/platform'
import PagedCollection from './PagedCollection.vue'
const commands = ref<AdminCommand[]>([]); const selected = ref<AdminCommand | null>(null); const status = ref(''); const loading = ref(false); const notice = ref('')
async function load() { loading.value = true; try { commands.value = await adminApi.commands({ status: status.value }) } catch (cause) { notice.value = cause instanceof Error ? cause.message : '命令记录读取失败' } finally { loading.value = false } }
async function show(id: string) { try { selected.value = await adminApi.command(id) } catch (cause) { notice.value = cause instanceof Error ? cause.message : '命令详情读取失败' } }
onMounted(load)
</script>
<template>
  <section class="commands-page"><header><div><h2>管理操作记录</h2><p>新操作直接执行并写入审计；历史待处理请求不会自动执行。执行结果、关联编号和失败原因集中查看。</p></div><div><select v-model="status" @change="load"><option value="">全部状态</option><option value="requested">历史待处理</option><option value="executed">已执行</option><option value="failed">失败</option><option value="rejected">已拒绝</option></select><button :disabled="loading" @click="load">刷新</button></div></header><p v-if="notice" class="notice">{{ notice }}</p><div class="layout"><section class="panel"><PagedCollection :items="commands" v-slot="{ items }"><button v-for="command in items" :key="command.id" class="row" @click="show(command.id)"><code>{{ command.id }}</code><b>{{ command.type }}</b><span>{{ command.actorName }} · {{ command.status }}</span><small v-if="command.failureReason">失败：{{ command.failureReason }}</small></button></PagedCollection><p v-if="!commands.length">暂无命令记录。</p></section><section class="panel detail"><template v-if="selected"><header><h3>命令详情</h3><button @click="selected = null">关闭</button></header><dl><dt>类型 / 状态</dt><dd>{{ selected.type }} · {{ selected.status }}</dd><dt>权限 / 作用域</dt><dd>{{ selected.permission }} · {{ selected.scope }}</dd><dt>关联 ID</dt><dd><code>{{ selected.correlationId }}</code></dd><dt>结果</dt><dd>{{ selected.resultMessage || selected.failureReason || '待处理' }}</dd></dl><pre>{{ JSON.stringify({ payload: selected.payload, result: selected.result }, null, 2) }}</pre></template><p v-else>选择一条命令查看详情。</p></section></div></section>
</template>
<style scoped>
.commands-page{display:grid;gap:14px}.commands-page>header,.commands-page>header>div{display:flex;align-items:flex-start;justify-content:space-between;gap:10px}.commands-page h2,.commands-page h3{margin:0 0 6px}.commands-page p,.commands-page span,.commands-page small{color:#89979d}.commands-page button,.commands-page select{min-height:38px;padding:7px 10px;border:1px solid #4b5961;background:#080e13;color:#fff}.layout{display:grid;grid-template-columns:minmax(320px,.8fr) minmax(0,1.2fr);gap:14px}.panel{min-width:0;padding:16px;border:1px solid #35424a;background:#0e161d}.row{display:grid;width:100%;grid-template-columns:minmax(0,1fr) minmax(120px,.7fr);gap:5px;border-width:1px 0 0!important;text-align:left}.row code,.row small{grid-column:1/-1;overflow-wrap:anywhere}.detail>header{display:flex;justify-content:space-between}.detail dl{display:grid;grid-template-columns:120px minmax(0,1fr);gap:8px}.detail dd{margin:0;overflow-wrap:anywhere}.detail pre{overflow:auto;padding:10px;background:#080e13;color:#aeb8bc}.notice{padding:10px;border-left:3px solid #d1b25c;background:#241c0a;color:#edd584!important}
@media(max-width:850px){.commands-page>header{flex-direction:column}.layout{grid-template-columns:1fr}.detail dl{grid-template-columns:1fr}}
</style>
