<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { getPublicContent } from '@/l12/platform'

const latestNews = ref('')
onMounted(async () => { try { latestNews.value = (await getPublicContent('home.latestNews')).value.trim() } catch {} })
</script>

<template><div class="news-page"><header><small>NEWS</small><h1>资讯</h1><p>官方公告、规则勘误、赛季更新与赛事信息的统一入口。</p></header><section class="news-layout"><main><article><time>{{ latestNews ? '最新公告' : '开发中' }}</time><h2>{{ latestNews ? '十二军团官方资讯' : '十二军团网页平台框架升级' }}</h2><p>{{ latestNews || '网站正在从单一对战入口扩展为官方网站、资料库、牌库社区和在线对战器。当前开发记录不会冒充正式官方公告。' }}</p><div><span>{{ latestNews ? '官方公告' : '平台更新' }}</span><b>阅读全文 →</b></div></article><div v-if="!latestNews" class="empty"><b>暂无已发布的正式资讯</b><span>管理员可在后台发布正式内容。</span></div></main><aside><h2>资讯分类</h2><a href="#" @click.prevent>官方公告 <span>{{ latestNews ? 1 : 0 }}</span></a><a href="#" @click.prevent>规则勘误 <span>0</span></a><a href="#" @click.prevent>赛季更新 <span>0</span></a><a href="#" @click.prevent>赛事信息 <span>0</span></a><router-link to="/rules">前往规则中心 <span>→</span></router-link></aside></section></div></template>

<style scoped>.news-page{min-height:100%;padding:0 clamp(18px,4vw,64px) 56px;font-family:'Microsoft YaHei','微软雅黑',sans-serif}.news-page>header{padding:34px 0 22px}.news-page>header small{color:#52c4cb;font:900 9px monospace;letter-spacing:.2em}.news-page h1{margin:6px 0;font-size:32px}.news-page>header p{margin:0;color:#7c898f;font-size:11px}.news-layout{display:grid;grid-template-columns:minmax(0,1fr) 280px;gap:14px}.news-layout main,.news-layout aside{border:1px solid #35424a;background:#0f171f}.news-layout article{padding:26px;border-bottom:1px solid #35424a}.news-layout time{color:#d9b65f;font-size:9px;font-weight:900}.news-layout article h2{margin:8px 0;font-size:21px}.news-layout article p{color:#8c979c;font-size:11px;line-height:1.8}.news-layout article>div{display:flex;justify-content:space-between;margin-top:20px;color:#56c4cb;font-size:10px;font-weight:900}.empty{display:flex;min-height:320px;flex-direction:column;align-items:center;justify-content:center;color:#707d84;text-align:center}.empty b{color:#9aa3a7}.empty span{margin-top:6px;font-size:10px}.news-layout aside{height:max-content;padding:20px}.news-layout aside h2{margin:0 0 12px;font-size:17px}.news-layout aside a{display:flex;justify-content:space-between;padding:13px 2px;border-bottom:1px solid rgba(235,230,216,.09);color:#a9b1b4;font-size:11px;text-decoration:none}.news-layout aside a span{color:#5ac5cc}@media(max-width:760px){.news-page{padding:0 12px 48px}.news-layout{grid-template-columns:1fr}.news-layout aside{grid-row:1}.news-layout article{padding:20px}}</style>
