<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { syncSavedDecksFromAccount, type SavedL12Deck } from '@/l12/decks'
import { connect, enterTournamentMatch, l12State, spectateTournamentMatch } from '@/l12/net'
import { hasPermission, platformState, tournamentApi, type Tournament, type TournamentMatch, type TournamentParticipant } from '@/l12/platform'
import { tournamentDeckVisibilityText, tournamentDisasterModeText, tournamentFormatText, tournamentMatchStatusText, tournamentPhaseText, tournamentResultText, tournamentRoundStatusText, tournamentStatusText } from '@/l12/tournamentLabels'
import { tournamentTimeControlLabel } from '@/l12/tournamentTime'
import TournamentJudgeDesk from './TournamentJudgeDesk.vue'
import TournamentManagementPanel from './TournamentManagementPanel.vue'

type Tab = 'overview'|'schedule'|'standings'|'participants'|'rules'|'judge'|'manage'
const route = useRoute(); const router = useRouter(); const tournament = ref<Tournament | null>(null)
const tab = ref<Tab>('overview'); const loading = ref(true); const busy = ref(false); const notice = ref('')
const deckName = ref(''); const savedDecks = ref<SavedL12Deck[]>([]); const dropArmed = ref(false)
const participantReasons = reactive<Record<string,string>>({}); const matchReasons = reactive<Record<string,string>>({})
const accountId = computed(() => platformState.account?.id || '')
const me = computed(() => tournament.value?.participants.find(item => item.accountId === accountId.value))
const canOrganize = computed(() => !!tournament.value && (tournament.value.organizerAccountId === accountId.value || hasPermission('tournaments.manage')))
const canJudge = computed(() => !!tournament.value && (canOrganize.value || tournament.value.referees.some(item => item.accountId === accountId.value) || hasPermission('tournaments.rulings.write')))
const canViewManage = computed(() => canOrganize.value || tournament.value?.pendingOrganizerTransfer?.toAccountId === accountId.value)
const rounds = computed(() => tournament.value?.rounds || [])

async function load() { loading.value = true; try { tournament.value = await tournamentApi.getByCode(String(route.params.code)); document.title = `${tournament.value.name} · 赛事中心` } catch (error) { notice.value = error instanceof Error ? error.message : '赛事不存在' } finally { loading.value = false } }
async function mutate(work: (item: Tournament) => Promise<Tournament>, success: string) { if (!tournament.value || busy.value) return; busy.value = true; try { tournament.value = await work(tournament.value); notice.value = success } catch (error) { notice.value = error instanceof Error ? error.message : '操作失败' } finally { busy.value = false } }
function register() { void mutate(item => tournamentApi.register(item.id, item.version), '报名成功；牌组将在赛前签到时锁定') }
function drop() { if (!dropArmed.value) { dropArmed.value = true; notice.value = '再次点击确认退出赛事；正式席位释放后会自动递补候补玩家'; return } void mutate(item => tournamentApi.drop(item.id, item.version), '已退出赛事；候补将自动递补') }
function preCheckIn() { void mutate(item => tournamentApi.preCheckIn(item.id, item.version, deckName.value, ''), '牌组快照已锁定，赛前签到完成') }
function remove(person: TournamentParticipant, ban: boolean) { const reason = participantReasons[person.accountId]?.trim(); if (!reason) { notice.value = '请先填写移出或限制理由'; return } void mutate(item => tournamentApi.removeParticipant(item.id, item.version, person.accountId, ban, reason), ban ? '玩家已移出并禁止再次报名' : '玩家已移出') }
function unban(person: TournamentParticipant) { const reason = participantReasons[person.accountId]?.trim(); if (!reason) { notice.value = '请先填写解除禁报名理由'; return } void mutate(item => tournamentApi.setRegistrationBan(item.id, item.version, person.accountId, false, reason), '已解除禁报名') }
function nextRound() { void mutate(item => tournamentApi.nextRound(item.id, item.version, '上一轮赛果已复核'), '下一轮配对已生成') }
function startRound(number: number) { void mutate(item => tournamentApi.startRound(item.id, number, item.version, '本轮签到状态已确认'), `第 ${number} 轮已开始`) }
function pauseRound(number: number, paused: boolean) { void mutate(item => tournamentApi.pauseRound(item.id, number, item.version, !paused, '工作人员控制整轮状态'), !paused ? '本轮已暂停' : '本轮已恢复') }
function pauseMatch(match: TournamentMatch) { const reason = matchReasons[match.id]?.trim(); if (!reason) { notice.value = '请先填写暂停或恢复本桌的理由'; return } void mutate(item => tournamentApi.pauseMatch(item.id, match.id, item.version, !match.paused, reason), match.paused ? '本桌已恢复' : '本桌已暂停') }
function roundCheckIn(roundNumber: number, ready: boolean) { void mutate(item => tournamentApi.checkIn(item.id, roundNumber, item.version, undefined, ready), ready ? '本轮到场已确认' : '已取消本轮到场状态') }
async function room(match: TournamentMatch, spectate: boolean) { if (!tournament.value) return; try { await connect(); spectate ? spectateTournamentMatch(tournament.value.id, match.id) : enterTournamentMatch(tournament.value.id, match.id); await new Promise<void>((resolve, reject) => { const started = Date.now(); const check = () => { if (l12State.game?.tournamentMatchId === match.id || l12State.room?.roomCode === match.roomCode) return resolve(); if (l12State.notice) return reject(new Error(l12State.notice)); if (Date.now() - started > 8_000) return reject(new Error('进入赛事房间超时，请留在本页重试')); window.setTimeout(check, 80) }; check() }); await router.push('/game') } catch (error) { notice.value = error instanceof Error ? error.message : '无法进入房间' } }
async function copyLink() { await navigator.clipboard.writeText(location.href); notice.value = '稳定赛事链接已复制' }
async function exportCsv() { if (!tournament.value) return; try { const blob = await tournamentApi.exportCsv(tournament.value.id); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `tournament-${tournament.value.code}.csv`; link.click(); URL.revokeObjectURL(link.href) } catch (error) { notice.value = error instanceof Error ? error.message : '导出失败' } }
const onResource = () => { void load() }; const onVisibility = () => { if (document.visibilityState === 'visible') void load() }
onMounted(() => { window.addEventListener('l12-resource-tournaments', onResource); document.addEventListener('visibilitychange', onVisibility); void Promise.all([load(), syncSavedDecksFromAccount().then(value => { savedDecks.value = Object.values(value); if (!deckName.value && savedDecks.value.length) deckName.value = savedDecks.value[0].name })]) })
onBeforeUnmount(() => { window.removeEventListener('l12-resource-tournaments', onResource); document.removeEventListener('visibilitychange', onVisibility) })
</script>

<template>
  <main class="detail-page">
    <button class="back" @click="router.push('/battle/tournaments')">← 返回赛事中心</button>
    <p v-if="loading">正在加载赛事…</p><p v-else-if="!tournament" class="notice">{{ notice }}</p>
    <template v-else>
      <header class="hero"><div><small>{{ tournament.code }} · {{ tournamentStatusText(tournament.status) }}</small><h1>{{ tournament.name }}</h1><p>{{ tournament.description || '暂无赛事简介' }}</p></div><div><button @click="copyLink">复制链接</button><button @click="exportCsv">导出 CSV</button></div></header>
      <aside v-if="tournament.status === 'canceled'" class="alert">赛事已取消：{{ tournament.cancellationReason || '请联系主办者了解详情' }}</aside>
      <aside v-else-if="me" class="next"><b>你的下一步</b><span v-if="me.waitlisted">当前候补第 {{ me.waitlistPosition }} 位，正式席位释放后会自动递补。</span><span v-else-if="tournament.status === 'registration' && !me.deck">开赛前请完成签到并锁定牌组。</span><span v-else-if="tournament.status === 'registration'">赛前签到已完成，请等待主办者开赛。</span><span v-else>查看下方赛程，进入自己的桌次。</span></aside>
      <nav class="tabs"><button v-for="item in ([['overview','概览'],['schedule','赛程'],['standings','排名'],['participants','参赛者'],['rules','规则'],['judge','裁判台'],...(canViewManage ? [['manage','主办管理']] : [])] as [Tab,string][] )" :key="item[0]" :class="{active: tab === item[0]}" @click="tab=item[0]">{{ item[1] }}</button></nav>
      <p v-if="notice" class="notice">{{ notice }}</p>
      <section v-if="tab === 'overview'" class="panel overview"><p><b>主办者</b>{{ tournament.organizerName }}</p><p><b>赛制</b>{{ tournamentFormatText(tournament.format) }}</p><p><b>人数</b>{{ tournament.counts.active }}/{{ tournament.maxPlayers }}（候补 {{ tournament.counts.waitlisted }}）</p><p><b>计划时间</b>{{ tournament.startAt ? new Date(tournament.startAt).toLocaleString('zh-CN') : '待定' }}</p><p><b>赛事阶段</b>{{ tournamentPhaseText(tournament.phase) }}</p><div v-if="tournament.postponements.length" class="wide"><h3>时间变更</h3><p v-for="item in tournament.postponements" :key="item.id">{{ new Date(item.newStartAt).toLocaleString('zh-CN') }} · {{ item.reason }}</p></div><div v-if="tournament.status === 'registration'" class="wide personal"><button v-if="!me" :disabled="busy || !tournament.registrationOpen" @click="register">{{ tournament.registrationOpen ? '报名（暂不提交牌组）' : '报名已关闭' }}</button><button v-else :disabled="busy" @click="drop">{{ dropArmed ? '确认退出赛事' : '退出赛事' }}</button><template v-if="me && !me.waitlisted && !me.deck"><select v-model="deckName"><option value="" disabled>选择账号牌组</option><option v-for="deck in savedDecks" :key="deck.name" :value="deck.name">{{ deck.name }}</option></select><button :disabled="busy || !deckName" @click="preCheckIn">签到并锁定牌组</button><span v-if="!savedDecks.length">账号中暂无可用牌组，请先到牌库创建并保存。</span></template></div></section>
      <section v-else-if="tab === 'schedule'" class="panel"><article v-for="round in rounds" :key="round.id" class="round"><h2>第 {{ round.number }} 轮 · {{ tournamentRoundStatusText(round.status) }}</h2><div v-if="canJudge" class="round-actions"><button v-if="round.status !== 'running' && round.status !== 'completed'" @click="startRound(round.number)">开始本轮</button><button v-if="round.status === 'running'" @click="pauseRound(round.number, round.paused)">{{ round.paused ? '恢复整轮' : '暂停整轮' }}</button><button v-if="round.status === 'completed' && tournament.status === 'running'" @click="nextRound">生成下一轮</button></div><div v-for="match in round.matches" :key="match.id" class="match"><span>第 {{ match.table }} 桌</span><b>{{ match.playerAName }} 对 {{ match.playerBName }}</b><span>{{ match.result ? tournamentResultText(match.result) : tournamentMatchStatusText(match.status) }}<em v-if="match.paused"> · 已暂停：{{ match.pauseReason }}</em></span><button v-if="match.playerAAccountId === accountId && !match.readyA && round.status === 'checkin'" @click="roundCheckIn(round.number,true)">本轮签到</button><button v-if="match.playerBAccountId === accountId && !match.readyB && round.status === 'checkin'" @click="roundCheckIn(round.number,true)">本轮签到</button><button v-if="match.canEnter" @click="room(match,false)">进入对局</button><button v-if="match.canSpectate" @click="room(match,true)">观战</button><template v-if="canJudge && match.status === 'running'"><input v-model.trim="matchReasons[match.id]" placeholder="暂停或恢复理由"><button @click="pauseMatch(match)">{{ match.paused ? '恢复本桌' : '暂停本桌' }}</button></template></div></article></section>
      <section v-else-if="tab === 'standings'" class="panel"><table><thead><tr><th>名次</th><th>玩家</th><th>胜-负-平</th><th>对手分</th></tr></thead><tbody><tr v-for="item in tournament.finalSwissStandings.length ? tournament.finalSwissStandings : rounds.at(-1)?.standings || []" :key="item.accountId"><td>{{ item.rank }}</td><td>{{ item.username }}</td><td>{{ item.wins }}-{{ item.losses }}-{{ item.draws }}</td><td>{{ item.opponentScore }}</td></tr></tbody></table></section>
      <section v-else-if="tab === 'participants'" class="panel"><article v-for="person in tournament.participants" :key="person.accountId" class="person"><span><b>{{ person.username }}</b><small v-if="person.waitlisted">候补 {{ person.waitlistPosition }}</small><small v-else-if="person.deck">已锁定牌组</small><small v-if="person.removed">已移出</small><small v-if="person.registrationBanned">禁止再次报名</small></span><span v-if="canOrganize && person.accountId !== tournament.organizerAccountId"><input v-model.trim="participantReasons[person.accountId]" placeholder="操作理由"><button v-if="!person.removed" @click="remove(person,false)">移出</button><button v-if="!person.removed" @click="remove(person,true)">移出并禁报名</button><button v-if="person.registrationBanned" @click="unban(person)">解除禁报名</button></span></article></section>
      <section v-else-if="tab === 'rules'" class="panel overview"><p><b>规则版本</b>{{ tournament.rules.ruleset }}</p><p><b>牌组公开</b>{{ tournamentDeckVisibilityText(tournament.rules.deckVisibility) }}</p><p><b>天灾范围</b>{{ tournamentDisasterModeText(tournament.rules.disasterMode) }}</p><p><b>计时规范</b>{{ tournamentTimeControlLabel(tournament.timeControl) }}</p><div class="wide"><h3>天灾卡池</h3><p>{{ tournament.rules.disasterCardIds.join('、') || '使用规则版本默认卡池' }}</p><h3>构筑限制</h3><p v-for="item in tournament.rules.cardRestrictions" :key="`${item.cardId}-${item.maxCopies}`">{{ item.cardId }}：最多 {{ item.maxCopies }} 张</p><p v-if="!tournament.rules.cardRestrictions.length">无额外构筑限制</p></div></section>
      <section v-else-if="tab === 'judge'" class="panel"><TournamentJudgeDesk :tournament="tournament" :can-judge="canJudge" @updated="value => tournament = value" @notice="value => notice = value" /></section>
      <section v-else-if="tab === 'manage'" class="panel"><TournamentManagementPanel :tournament="tournament" :account-id="accountId" :can-organize="canOrganize" @updated="value => tournament = value" @notice="value => notice = value" /></section>
    </template>
  </main>
</template>

<style scoped>
.detail-page{max-width:1180px;margin:0 auto;padding:28px 24px 64px;display:grid;gap:18px}.back{justify-self:start}.hero{display:flex;justify-content:space-between;gap:20px;align-items:end}.hero h1{margin:6px 0}.hero p,.notice{color:var(--muted)}.hero>div:last-child{display:flex;gap:8px}.alert,.next{padding:14px 16px;border:1px solid var(--border);border-radius:10px}.next{display:flex;gap:14px}.tabs{display:flex;gap:4px;border-bottom:1px solid var(--border);overflow:auto}.tabs button{border:0;background:transparent;padding:12px;color:inherit;white-space:nowrap}.tabs .active{border-bottom:2px solid var(--accent)}.panel{padding:18px;border:1px solid var(--border);border-radius:12px;background:var(--panel)}.overview{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.overview p{display:grid;gap:5px}.wide{grid-column:1/-1}.personal{display:flex;gap:8px;flex-wrap:wrap}.round{display:grid;gap:8px}.match,.person{display:flex;align-items:center;gap:12px;padding:10px;border-top:1px solid var(--border)}.match b{flex:1}.match em{color:var(--danger);font-style:normal}.person{justify-content:space-between}.person>span{display:flex;gap:8px;align-items:center}.person small{color:var(--muted)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid var(--border)}@media(max-width:680px){.detail-page{padding:20px 12px}.hero{align-items:start}.overview{grid-template-columns:1fr}.wide{grid-column:auto}.match{align-items:flex-start;flex-wrap:wrap}.match b{flex-basis:70%}}
</style>
