import type { SavedL12Deck } from './decks'
import { DeckCodeReader, crc32, readCardId, writeCardId, writeVarint } from './deckCodeCodec'

/** A storage representation only: this module neither reads nor writes browser storage. */
export interface EncodedDeckCache {
  version: 1
  code: string
}

export const DECK_CACHE_LIMITS = Object.freeze({
  bytes: 256 * 1024,
  metadataBytes: 192 * 1024,
  cardIdBytes: 128,
  cardsPerSection: 512,
  benchCards: 200,
  artCards: 128,
  artCopies: 50,
  artIdBytes: 256,
})

const PREFIX = 'L12C1-'
const BASE64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_'
const METADATA_KEYS = [
  'id', 'revision', 'name', 'updatedAt', 'publicationId', 'publicationVersion',
  'alternateArtSelections', 'alternateArtCopies',
] as const
const FIELD_KEYS = new Set<string>([
  ...METADATA_KEYS, 'masterId', 'cardIds', 'moraleIds', 'specialIds', 'benchIds',
])
const encoder = new TextEncoder()
const decoder = new TextDecoder('utf-8', { fatal: true })
const owns = (value: object, key: PropertyKey) => Object.prototype.hasOwnProperty.call(value, key)

function invalid(reason: string): never {
  throw new Error(`牌库缓存${reason}`)
}

function record(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value)
    && Object.getPrototypeOf(value) === Object.prototype
}

function validText(value: unknown, limit: number): value is string {
  return typeof value === 'string' && value.length <= limit && encoder.encode(value).length <= limit
    && decoder.decode(encoder.encode(value)) === value
}

function validateCards(value: unknown, maximum: number): asserts value is string[] {
  if (!Array.isArray(value) || Object.getPrototypeOf(value) !== Array.prototype || value.length > maximum
    || Reflect.ownKeys(value).length !== value.length + 1) invalid('卡牌字段或数量超出限制')
  for (const id of value) if (!validText(id, DECK_CACHE_LIMITS.cardIdBytes)) invalid('卡牌字段或数量超出限制')
}

function validateArt(value: unknown, copies: boolean) {
  if (!record(value) || Reflect.ownKeys(value).length > DECK_CACHE_LIMITS.artCards
    || Reflect.ownKeys(value).some(key => !Object.prototype.propertyIsEnumerable.call(value, key))) invalid('异画字段超出限制')
  for (const key of Reflect.ownKeys(value)) {
    if (!validText(key, DECK_CACHE_LIMITS.cardIdBytes)) invalid('异画卡牌标识无效')
    const item = value[key]
    if (copies) {
      if (!Array.isArray(item) || Object.getPrototypeOf(item) !== Array.prototype || item.length > DECK_CACHE_LIMITS.artCopies
        || Reflect.ownKeys(item).length !== item.length + 1) invalid('逐副本异画字段无效')
      for (const id of item) if (!validText(id, DECK_CACHE_LIMITS.artIdBytes)) invalid('逐副本异画字段无效')
    } else if (!validText(item, DECK_CACHE_LIMITS.artIdBytes)) invalid('异画标识无效')
  }
}

function validateDeck(value: unknown): asserts value is SavedL12Deck {
  if (!record(value) || Reflect.ownKeys(value).some(key => typeof key !== 'string' || !FIELD_KEYS.has(key))) {
    invalid('字段未知或格式无效')
  }
  for (const key of ['name', 'updatedAt', 'masterId', 'cardIds', 'moraleIds', 'specialIds']) {
    if (!owns(value, key)) invalid('缺少必要字段')
  }
  // Names are not truncated, and timestamps are never generated by this format.
  if (typeof value.name !== 'string' || value.name.length > DECK_CACHE_LIMITS.metadataBytes
    || typeof value.updatedAt !== 'string' || value.updatedAt.length > DECK_CACHE_LIMITS.metadataBytes
    || !validText(value.masterId, DECK_CACHE_LIMITS.cardIdBytes)) invalid('名称、时间或主宰字段无效')
  validateCards(value.cardIds, DECK_CACHE_LIMITS.cardsPerSection)
  validateCards(value.moraleIds, DECK_CACHE_LIMITS.cardsPerSection)
  validateCards(value.specialIds, DECK_CACHE_LIMITS.cardsPerSection)
  if (value.benchIds !== undefined) validateCards(value.benchIds, DECK_CACHE_LIMITS.benchCards)
  if (value.id !== undefined && (typeof value.id !== 'string' || value.id.length > DECK_CACHE_LIMITS.metadataBytes)) invalid('牌库身份无效')
  for (const key of ['revision', 'publicationVersion']) {
    const item = value[key]
    if (key === 'publicationVersion' && item === null) continue
    if (item !== undefined && (typeof item !== 'number' || !Number.isSafeInteger(item) || item < 1)) {
      invalid('修订或公开版本无效')
    }
  }
  if (value.publicationId !== undefined && value.publicationId !== null
    && (typeof value.publicationId !== 'string' || value.publicationId.length > DECK_CACHE_LIMITS.metadataBytes)) invalid('公开引用无效')
  if (value.alternateArtSelections !== undefined) validateArt(value.alternateArtSelections, false)
  if (value.alternateArtCopies !== undefined) validateArt(value.alternateArtCopies, true)
}

function writeOrderedCards(output: number[], cards: readonly string[]) {
  const runs: Array<[string, number]> = []
  for (const card of cards) {
    const previous = runs.at(-1)
    if (previous?.[0] === card) previous[1]++
    else runs.push([card, 1])
  }
  writeVarint(output, runs.length)
  for (const [card, quantity] of runs) {
    writeCardId(output, card)
    writeVarint(output, quantity)
  }
}

function readOrderedCards(reader: DeckCodeReader, maximum: number): string[] {
  const runs = reader.varint()
  if (runs > maximum) invalid('卡牌段数超出限制')
  const cards: string[] = []
  for (let index = 0; index < runs; index++) {
    const id = readCardId(reader)
    const quantity = reader.varint()
    if (quantity < 1 || cards.length + quantity > maximum) invalid('卡牌数量无效')
    for (let copy = 0; copy < quantity; copy++) cards.push(id)
  }
  return cards
}

function encodeBase64(bytes: Uint8Array): string {
  const parts: string[] = []
  for (let index = 0; index < bytes.length; index += 3) {
    const remaining = bytes.length - index
    const value = (bytes[index]! << 16) | ((bytes[index + 1] ?? 0) << 8) | (bytes[index + 2] ?? 0)
    parts.push(BASE64[value >>> 18]!, BASE64[(value >>> 12) & 63]!)
    if (remaining > 1) parts.push(BASE64[(value >>> 6) & 63]!)
    if (remaining > 2) parts.push(BASE64[value & 63]!)
  }
  return parts.join('')
}

function decodeBase64(text: string): Uint8Array {
  if (!text || text.length % 4 === 1 || !/^[A-Za-z0-9_-]+$/.test(text)) invalid('编码格式无效')
  const bytes: number[] = []
  for (let index = 0; index < text.length; index += 4) {
    const size = Math.min(4, text.length - index)
    const value = (BASE64.indexOf(text[index]!) << 18) | (BASE64.indexOf(text[index + 1]!) << 12)
      | ((size > 2 ? BASE64.indexOf(text[index + 2]!) : 0) << 6)
      | (size > 3 ? BASE64.indexOf(text[index + 3]!) : 0)
    bytes.push(value >>> 16)
    if (size > 2) bytes.push((value >>> 8) & 255)
    if (size > 3) bytes.push(value & 255)
  }
  const result = Uint8Array.from(bytes)
  if (result.length > DECK_CACHE_LIMITS.bytes || encodeBase64(result) !== text) invalid('编码非规范或超出限制')
  return result
}

export function encodeDeckCache(deck: SavedL12Deck): EncodedDeckCache {
  validateDeck(deck)
  const metadata: Record<string, unknown> = {}
  let present = 0
  let undefinedValues = 0
  METADATA_KEYS.forEach((key, index) => {
    if (!owns(deck, key)) return
    present |= 1 << index
    if (deck[key] === undefined) undefinedValues |= 1 << index
    else metadata[key] = deck[key]
  })
  const metadataBytes = encoder.encode(JSON.stringify(metadata))
  if (metadataBytes.length > DECK_CACHE_LIMITS.metadataBytes) invalid('元数据超出容量限制')
  const output = [1]
  writeVarint(output, present)
  writeVarint(output, undefinedValues)
  writeVarint(output, metadataBytes.length)
  // Avoid argument-count limits for large but valid metadata records.
  for (const byte of metadataBytes) output.push(byte)
  writeCardId(output, deck.masterId)
  writeOrderedCards(output, deck.cardIds)
  writeOrderedCards(output, deck.moraleIds)
  writeOrderedCards(output, deck.specialIds)
  const benchState = !owns(deck, 'benchIds') ? 0 : deck.benchIds === undefined ? 1 : 2
  output.push(benchState)
  if (benchState === 2) writeOrderedCards(output, deck.benchIds!)
  if (output.length + 4 > DECK_CACHE_LIMITS.bytes) invalid('超出容量限制')
  const checksum = crc32(Uint8Array.from(output))
  output.push(checksum >>> 24, (checksum >>> 16) & 255, (checksum >>> 8) & 255, checksum & 255)
  return { version: 1, code: PREFIX + encodeBase64(Uint8Array.from(output)) }
}

export function decodeDeckCache(value: unknown): SavedL12Deck {
  if (!record(value) || value.version !== 1) invalid('版本不受支持')
  if (Reflect.ownKeys(value).some(key => key !== 'version' && key !== 'code')
    || typeof value.code !== 'string' || !value.code.startsWith(PREFIX)) invalid('封装格式无效')
  if (value.code.length > PREFIX.length + Math.ceil(DECK_CACHE_LIMITS.bytes / 3) * 4) invalid('超出容量限制')
  const bytes = decodeBase64(value.code.slice(PREFIX.length))
  if (bytes.length < 5) invalid('内容不完整')
  const body = bytes.subarray(0, -4)
  const expected = ((bytes.at(-4)! << 24) | (bytes.at(-3)! << 16)
    | (bytes.at(-2)! << 8) | bytes.at(-1)!) >>> 0
  if (crc32(body) !== expected) invalid('校验失败')
  const reader = new DeckCodeReader(body)
  if (reader.byte() !== 1) invalid('正文版本不受支持')
  const present = reader.varint()
  const undefinedValues = reader.varint()
  if (present > 255 || undefinedValues > 255 || (undefinedValues & ~present) !== 0) invalid('字段标记无效')
  let metadata: unknown
  try { metadata = JSON.parse(reader.string(DECK_CACHE_LIMITS.metadataBytes)) }
  catch { invalid('元数据损坏或超出限制') }
  if (!record(metadata)) invalid('元数据格式无效')
  const definedKeys = METADATA_KEYS.filter((_, index) => (present & (1 << index)) && !(undefinedValues & (1 << index)))
  if (Reflect.ownKeys(metadata).length !== definedKeys.length
    || definedKeys.some(key => !owns(metadata, key))) invalid('元数据字段不匹配')
  const deck: Record<string, unknown> = { ...metadata }
  METADATA_KEYS.forEach((key, index) => { if (undefinedValues & (1 << index)) deck[key] = undefined })
  deck.masterId = readCardId(reader)
  deck.cardIds = readOrderedCards(reader, DECK_CACHE_LIMITS.cardsPerSection)
  deck.moraleIds = readOrderedCards(reader, DECK_CACHE_LIMITS.cardsPerSection)
  deck.specialIds = readOrderedCards(reader, DECK_CACHE_LIMITS.cardsPerSection)
  const benchState = reader.byte()
  if (benchState === 1) deck.benchIds = undefined
  else if (benchState === 2) deck.benchIds = readOrderedCards(reader, DECK_CACHE_LIMITS.benchCards)
  else if (benchState !== 0) invalid('备选池字段标记无效')
  if (!reader.done) invalid('存在多余正文')
  validateDeck(deck)
  return deck
}
