param(
    [string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$OutputPath = 'docs/l12/LEGACY-EFFECT-MIGRATION.md'
)

$ErrorActionPreference = 'Stop'
$serverProject = Get-ChildItem -LiteralPath $ProjectRoot -Recurse -Filter 'GrandUMIServer.csproj' -File | Select-Object -First 1
if ($null -eq $serverProject) { throw 'GrandUMIServer.csproj not found.' }
$sourcePath = Join-Path $serverProject.DirectoryName 'TwelveLegions'
$dataPath = Join-Path $sourcePath 'Data'
$cards = @{}
foreach ($fileName in @('cards.s1.json', 'cards.s2.json')) {
    $decoded = [System.IO.File]::ReadAllText((Join-Path $dataPath $fileName), [System.Text.Encoding]::UTF8) | ConvertFrom-Json
    foreach ($card in $decoded) { $cards[$card.id] = $card }
}

$rows = New-Object System.Collections.Generic.List[object]
foreach ($file in Get-ChildItem -LiteralPath $sourcePath -Filter 'L12*.cs' -File) {
    $lines = [System.IO.File]::ReadAllLines($file.FullName, [System.Text.Encoding]::UTF8)
    for ($index = 0; $index -lt $lines.Length; $index++) {
        if ($lines[$index] -notmatch 'case\s+"(?<id>S\d{2}-[A-Za-z0-9]+)"') { continue }
        $id = $Matches.id
        $method = ''
        for ($cursor = $index; $cursor -ge 0; $cursor--) {
            if ($lines[$cursor] -match '^\s*(?:private|public|internal)\s+.*\(') {
                $method = ($lines[$cursor] -replace '\s+', ' ').Trim()
                break
            }
        }
        $card = $cards[$id]
        $trigger = switch -Regex ($method) {
            'PromotionEnter' { 'promotion-enter'; break }
            'AfterAttack' { 'after-attack'; break }
            'AfterDamage' { 'after-damage'; break }
            'Enter' { 'enter'; break }
            'Tactic' { 'play'; break }
            'Attack' { 'attack'; break }
            'Death' { 'death'; break }
            'Leave' { 'leave'; break }
            'Reaction' { 'reaction'; break }
            'Disaster' { 'disaster'; break }
            'Active' { 'active'; break }
            'Abilities' { 'ability-view'; break }
            default { 'unknown' }
        }
        $rows.Add([ordered]@{
            CardId = $id
            Name = if ($null -eq $card) { '' } else { $card.nameZh }
            Trigger = $trigger
            File = $file.Name
            Line = $index + 1
            Method = $method
        })
    }
}

$target = if ([System.IO.Path]::IsPathRooted($OutputPath)) { $OutputPath } else { Join-Path $ProjectRoot $OutputPath }
$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('# Legacy card-id branch migration inventory')
[void]$builder.AppendLine()
[void]$builder.AppendLine('> Generated by `scripts/export-l12-legacy-effect-inventory.ps1` for migration auditing only; this is not a card-rules source.')
[void]$builder.AppendLine()
[void]$builder.AppendLine("- Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss zzz')")
[void]$builder.AppendLine("- Branches: $($rows.Count)")
[void]$builder.AppendLine("- Cards: $(@($rows.CardId | Sort-Object -Unique).Count)")
[void]$builder.AppendLine()
[void]$builder.AppendLine('| Card ID | Name | Timing | File:line | Method |')
[void]$builder.AppendLine('|---|---|---|---|---|')
foreach ($row in $rows | Sort-Object File, Line) {
    $method = $row.Method.Replace('|', '\|')
    [void]$builder.AppendLine("| $($row.CardId) | $($row.Name) | $($row.Trigger) | $($row.File):$($row.Line) | $method |")
}
[System.IO.Directory]::CreateDirectory([System.IO.Path]::GetDirectoryName($target)) | Out-Null
[System.IO.File]::WriteAllText($target, $builder.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Legacy effect inventory written: $target"
